### ISSUE TITLE
[style] improve UI following styleguide

### ISSUE THREAD

**Issue by francescogior** [buildo/rc-datepicker#81]
## requirements

- [https://paper.dropbox.com/doc/DATEPICKER-UYR7YaYMCTaJsTHV922mn](https://paper.dropbox.com/doc/DATEPICKER-UYR7YaYMCTaJsTHV922mn)

![image](https://cloud.githubusercontent.com/assets/3280300/15533446/f86555f6-2264-11e6-87c4-bd461ad569e1.png)

## sub-issues

- [x] update style with new mockup #98 **[FrancescoCioria]**

**Comment by FrancescoCioria** [comment]
still missing:
- datepicker:
  - pointer at the top
  - icons for left/right arrows
  - days should be rectangles
  - global border-radius
  - font-size
- input:
  - bold when date is valid
  - icon calendar
  - icon x
  - invert calendar and x icons
  - icon x should be blue? (why?)
  - border-radius

**Comment by francescogior** [comment]
## Requirements recap
- [ ] datepicker should have a triangular pointer towards the input/button
- [ ] datepicker's border-radius should be 2px, as for the input/button's
- [ ] adjust font-size as indicated in the linked paper
- [ ] adjust days cells' size, to make it look like rectangles
- [ ] icons: add props to pass icon classNames for left/right arrow in datepicker (as for the other icons)
- [ ] font-weight should be bold when a date is selected

**Comment by sawsanias** [comment]
Regarding the req.
 adjust font-size as indicated in the linked paper

The font-size set in the project is the same as the specified one in the paper of the component.

**Comment by sawsanias** [comment]
The current size of the cell seems equal to the one specified in the component's paper
